title: "Gonardiya"

description: >
  Gonardiya represents origin, heritage, intellectual identity,
  continuity and legacy.

url: ""
baseurl: ""

lang: "en-IN"

author:
  name: "Gonardiya"

logo: "/assets/gonardiya.png"

markdown: kramdown

permalink: /:basename/

timezone: Asia/Kolkata

collections:
  pages:
    output: true
    permalink: /:name/

defaults:

  - scope:
      path: ""
    values:
      layout: default
      lang: "en-IN"
      robots: "index,follow"

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: default
      lang: "en-IN"
      robots: "index,follow"

plugins:
  - jekyll-sitemap
